config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#home'
  resources :lists
  resources :payments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :lists, through: :list_items
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_items
  has_many :payments
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :item, foreign_key: 'item_id'
  belongs_to :list, foreign_key: 'list_id'
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :list

  def create_stripe_payment(email, token, amount)
    customer = Stripe::Customer.create(
      :email => email,
      :source  => token
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => amount,
      :description => 'Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    raise "Error processing card"
    # flash[:error] = e.message
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
  has_many :payments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def home
    @items = Item.all
    @list = List.where(user_id: current_user.id, has_paid: false).first
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    
  end

  def create
    @item = Item.find(params[:item].to_i)
    check_if_list_exists
    ListItem.create(list_id: @list.id, item_id: @item.id)
    update_total(@item)
    flash[:notice] = 'The item has been added to your cart'
    redirect_to root_path
  end

  private

  def check_if_list_exists
    @list = List.where(user_id: current_user.id, has_paid: false).first
    if !@list.present?
      @list = List.create(user_id: current_user.id, has_paid: false, total_amount: 0)
    end
  end

  def update_total(item)
    new_total = @list.total_amount + item.price
    @list.update_attributes(total_amount: new_total)
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @list = List.where(user_id: current_user.id, has_paid: false).first
    @payment = Payment.new(amount: @list.total_amount, user_id: current_user.id, list_id: @list.id)
  end

  def create
    @payment = Payment.new(payment_params)
    @list = List.find(@payment.list_id)
    response = @payment.create_stripe_payment(params[:stripeEmail], params[:stripeToken], @payment.amount)
    if response.status === 'succeeded'
      @list.update_attributes(has_paid: true)
      @payment.payment_successful = true
      @payment.save!
      flash[:notice] = 'Your payment was successful'
      redirect_to root_path
    else
      @payment.payment_successful = false
      @payment.save!
      flash[:alert] = 'Your card has been declined'
      redirect_to new_payment_path
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:amount, :user_id, :list_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/application/home.html.erb
<div class='container'>
  <div class='card-display'>
    <% @items.each do |f| %>
      <div class="card">
        <div class='display-img'>
          <%= image_tag(f.photo_url, alt: 'card image', class: 'card-img-top img-adj')  %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= f.name %></h5>
          <p class="card-text">
            <%= f.description %>
          </p>
          <% if current_user %>
            <%= link_to 'Add to Cart', lists_path(item: f), method: :post, class: 'btn btn-primary' %>
          <% else %>
            <%= link_to 'Purchase', new_user_session_path, class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_alert.html.erb
<% if alert %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-danger"><%= alert %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
  <a class="navbar-brand" href="/">Sample Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      
      
    </ul>
    <ul class="navbar-nav navbar-right">
      <% if current_user %>
        <li class="nav-item">
          <% if @list.present? && @list.has_paid === false %>
            <%= link_to new_payment_path, class: 'nav-link' do %>
              <%= "Checkout (#{@list.list_items.count})" %>
            <% end %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% if notice %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-success"><%= notice.html_safe %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/notice' %>
    <%= render 'layouts/alert' %>
    <%= yield %>
  </body>
</html>

app/views/payments/new.html.erb
<div class='container'>
  <ul>
    <% @list.list_items.each do |f| %>
      <li>
        <%= f.item.name %>
        $<%= f.item.price%>
      </li>
    <% end %>
  </ul>

  <%= form_for @payment do |f| %>
    <article>
      <% if flash[:error].present? %>
        <div id='error_explanation'>
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class='amount'>
        <span>Amount: $<%= @list.total_amount %></span>
      </label>
      <%= f.hidden_field :list_id, value: "#{@payment.list_id}" %>
      <%= f.hidden_field :user_id, value: "#{@payment.user_id}" %>
      <%= f.hidden_field :amount, value: "#{@payment.amount}" %>

    </article>

    <script src='https://checkout.stripe.com/checkout.js' class='stripe-button'
            data-key='<%= Rails.configuration.stripe[:publishable_key] %>'
            data-description='Cell phone purchase'
            data-amount=<%= "#{@list.total_amount.to_s}00"%>
            data-locale='auto'></script>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>